### ISSUE TITLE
Unable to move robot arm

### ISSUE THREAD

**Issue by Jabro** [a2s-institute/youbot_simulation#2]
Hello,

unfortunately I'm still unable to move the robot arm. 

I only started `roslaunch youbot_gaezbo_robots youbot.launch`. I don't know wether this should suffice. I tried to launch `youbot_gazebo_controll joint_state_controller.launch`, too. The node quits after a time out, because it doesn't find the controller: `Controller Spawner couldn't find the expected controller_manager ROS interface.` The same is the case for the arm launch.

I noticed the following in the gazebo log:
`Failed to load plugin libgazebo_ros_control.so: libgazebo_ros_control.so: cannot open shared object file: No such file or directory`

However if I install the package I get the following error messages trying to start `roslaunch youbot_gaezbo_robots youbot.launch`:

`[ERROR] [1399308724.111111477, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wheel_joint_fl
[ERROR] [1399308724.112505600, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/caster_joint_fl
[ERROR] [1399308724.113759171, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wheel_joint_fr
[ERROR] [1399308724.115263875, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/caster_joint_fr
[ERROR] [1399308724.116495614, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wheel_joint_bl
[ERROR] [1399308724.117715684, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/caster_joint_bl
[ERROR] [1399308724.118911858, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wheel_joint_br
[ERROR] [1399308724.120136013, 1.265000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/caster_joint_br
[ INFO] [1399308724.159508814, 1.265000000]: Loaded gazebo_ros_control.
[INFO] [WallTime: 1399308724.215129] [1.314000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1399308724.217279] [1.315000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1399308724.219715] [1.317000] Loading controller: arm_1/arm_controller
[ERROR] [1399308724.223479380, 1.320000000]: Could not load controller 'arm_1/arm_controller' because controller type 'effort_controllers/JointTrajectoryController' does not exist.
[ERROR] [1399308724.224154551, 1.322000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[INFO] [WallTime: 1399308724.241662] [1.340000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1399308724.243857] [1.341000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1399308724.252170] [1.347000] Loading controller: arm_1/gripper_controller
[ERROR] [1399308724.259030340, 1.354000000]: Could not load controller 'arm_1/gripper_controller' because controller type 'effort_controllers/JointTrajectoryController' does not exist.
[ERROR] [1399308724.259100488, 1.354000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[INFO] [WallTime: 1399308724.265240] [1.359000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1399308724.267523] [1.362000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1399308724.269528] [1.364000] Loading controller: joint_state_controller
[ERROR] [1399308724.272590982, 1.367000000]: Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist.
[ERROR] [1399308724.272663807, 1.367000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1399308725.224773] [2.283000] Failed to load arm_1/arm_controller
[INFO] [WallTime: 1399308725.225360] [2.283000] Controller Spawner: Loaded controllers: 
[INFO] [WallTime: 1399308725.230433] [2.289000] Started controllers: 
[ERROR] [WallTime: 1399308725.260404] [2.317000] Failed to load arm_1/gripper_controller
[INFO] [WallTime: 1399308725.260797] [2.317000] Controller Spawner: Loaded controllers: 
[INFO] [WallTime: 1399308725.264447] [2.320000] Started controllers: 
[ERROR] [WallTime: 1399308725.273905] [2.330000] Failed to load joint_state_controller
[INFO] [WallTime: 1399308725.274253] [2.330000] Controller Spawner: Loaded controllers: 
[INFO] [WallTime: 1399308725.277456] [2.334000] Started controllers:``

I also get several warnings about missing materials. 

Strangely enough, I am still able to move the robot base by publishing to /cmd_vel

**Comment by Jabro** [comment]
Ok the arm seems to move despite the error messages, but it moves really slowly. It is so slow, that it seems, it is not moving. I also couldn't verify whether the movement is correct.

**Comment by frederikhegger** [comment]
If you pull the recent changes for this repository you get rid of the warning "[1399308724.118911858, 1.265000000]: No p gain specified for pid ...." (fixed with commit https://github.com/mas-group/youbot_simulation/commit/96d8af10dedf5806080170edeb3f410ee6853926)

Additionally you are missing to more packages namely "ros-hydro-effort-controllers" and "ros-hydro-joint-state-controller" (see error messages "Could not load controller 'joint_state_controller' because controller type 'joint_state_controller/JointStateController' does not exist." and "Could not load controller 'arm_1/arm_controller' because controller type 'effort_controllers/JointTrajectoryController' does not exist."

**Comment by Jabro** [comment]
just noticed that I was using the version from the youBot repository which is several commits behind.

After having installed the ros-hydro-joint-state-controller package the corresponding error message doesn't show up anymore.

However installing the ros-hydro-effort-controllers package didn't make any change. "rosmgs package effort_controllers" does not show any message types in this package.

**Comment by frederikhegger** [comment]
They are plugins, not messages. Did you try to move the arm through the trajectory action?

**Comment by Jabro** [comment]
Yes as I said it worked despite the errors but horribly slow. 
At the moment gazebo doesn't even start. I think there are some issues with the graphics driver (switched back to mesa because of issues with fglrx, but still facing issues and may have to switch to fglrx again and hope they are away).

**Comment by frederikhegger** [comment]
One reason why the simulation was so slow in the past, was that we were abusing the move_planar plugin as a base controller in Gazebo. This has been solved by using a proper base controller now. 

And now, the arm is also moving in a regular speed.
